#!/usr/bin/env python3
"""
Generate Clang-optimized NEON FP32 packed GEMM microkernels.

Outputs a complete C++ source file with:
  - pack_a / pack_b functions (contiguous packed layout)
  - Microkernel with vfmaq_laneq_f32 (.s[N] fused FMLA)
  - Registry wrapper + auto-registration

Usage:
  python3 gen_neon_gemm.py <Mr> <Nr> <K_unroll> <priority>
  python3 gen_neon_gemm.py 4 16 4 110 > src/gemm/generated/neon_fp32_4x16.cpp
"""

import sys
import math


def ceil_div(a, b):
    return (a + b - 1) // b


def gen_header(mr, nr, k_unroll):
    n_b = nr // 4
    n_a = ceil_div(mr, 4)
    total_acc = mr * n_b
    regs_per_pass = total_acc + n_b + n_a

    rows_per_pass = (32 - n_b - n_a) // n_b
    n_passes = ceil_div(mr, rows_per_pass)

    return f"""\
/// @file neon_fp32_{mr}x{nr}.cpp
/// Auto-generated packed {mr}x{nr} FP32 NEON micro-kernel.
/// Generated by: tools/gen_neon_gemm.py
///   Mr={mr}, Nr={nr}, K_unroll={k_unroll}
///   Register budget: {total_acc} acc + {n_b} B + {n_a} A = {regs_per_pass} regs
///   {'1-pass (fits in 32 regs)' if regs_per_pass <= 32 else f'{n_passes}-pass (rows_per_pass={rows_per_pass})'}

#include "dnnopt/gemm/gemm_config.h"
#include "dnnopt/gemm/gemm_ukernel_registry.h"

#include <algorithm>
#include <cstring>

#ifdef __ARM_NEON
#include <arm_neon.h>
#endif

#ifdef __aarch64__

namespace dnnopt {{
"""


def gen_pack_a(mr, nr):
    lines = []
    lines.append(f"// ============================================================")
    lines.append(f"// Pack A: {mr} contiguous floats per K")
    lines.append(f"// ============================================================")
    lines.append("")
    lines.append(f"static void pack_a_fp32_{mr}x{nr}(")
    lines.append(f"        int m_len, int k_len,")
    lines.append(f"        const float* A, int lda,")
    lines.append(f"        float* packed_A) {{")
    lines.append(f"    constexpr int Mr = {mr};")
    lines.append(f"    for (int i = 0; i < m_len; i += Mr) {{")
    lines.append(f"        int m_rem = std::min(Mr, m_len - i);")
    lines.append(f"        if (m_rem == Mr) {{")
    lines.append(f"            for (int k = 0; k < k_len; ++k) {{")

    # Full tile: store Mr contiguous values
    for r in range(mr):
        lines.append(f"                packed_A[{r}] = A[(i + {r}) * lda + k];")
    lines.append(f"                packed_A += {mr};")
    lines.append(f"            }}")
    lines.append(f"        }} else {{")
    lines.append(f"            for (int k = 0; k < k_len; ++k) {{")
    lines.append(f"                int r = 0;")
    lines.append(f"                for (; r < m_rem; ++r)")
    lines.append(f"                    packed_A[r] = A[(i + r) * lda + k];")
    lines.append(f"                for (; r < Mr; ++r)")
    lines.append(f"                    packed_A[r] = 0.0f;")
    lines.append(f"                packed_A += {mr};")
    lines.append(f"            }}")
    lines.append(f"        }}")
    lines.append(f"    }}")
    lines.append(f"}}")
    return "\n".join(lines)


def gen_pack_b(mr, nr):
    n_quads = nr // 4
    lines = []
    lines.append("")
    lines.append(f"// ============================================================")
    lines.append(f"// Pack B: {nr} contiguous floats per K ({n_quads} quads)")
    lines.append(f"// ============================================================")
    lines.append("")
    lines.append(f"static void pack_b_fp32_{mr}x{nr}(")
    lines.append(f"        int k_len, int n_len,")
    lines.append(f"        const float* B, int ldb,")
    lines.append(f"        float* packed_B) {{")
    lines.append(f"    constexpr int Nr = {nr};")
    lines.append(f"    for (int j = 0; j < n_len; j += Nr) {{")
    lines.append(f"        int n_rem = std::min(Nr, n_len - j);")
    lines.append(f"        if (n_rem == Nr) {{")

    # Full tile: NEON-accelerated copy
    lines.append(f"            for (int k = 0; k < k_len; ++k) {{")
    lines.append(f"                const float* src = &B[k * ldb + j];")
    for q in range(n_quads):
        lines.append(f"                vst1q_f32(packed_B + {q * 4}, vld1q_f32(src + {q * 4}));")
    lines.append(f"                packed_B += Nr;")
    lines.append(f"            }}")

    lines.append(f"        }} else {{")
    lines.append(f"            for (int k = 0; k < k_len; ++k) {{")
    lines.append(f"                const float* src = &B[k * ldb + j];")
    lines.append(f"                int c = 0;")
    lines.append(f"                for (; c < n_rem; ++c)")
    lines.append(f"                    packed_B[c] = src[c];")
    lines.append(f"                for (; c < Nr; ++c)")
    lines.append(f"                    packed_B[c] = 0.0f;")
    lines.append(f"                packed_B += Nr;")
    lines.append(f"            }}")
    lines.append(f"        }}")
    lines.append(f"    }}")
    lines.append(f"}}")
    return "\n".join(lines)


def gen_kernel(mr, nr, k_unroll):
    n_b = nr // 4  # number of B quads
    n_a = ceil_div(mr, 4)  # number of A quads

    lines = []
    lines.append("")
    lines.append(f"// ============================================================")
    lines.append(f"// Packed {mr}x{nr} NEON micro-kernel ({k_unroll}x K-unrolled)")
    lines.append(f"// ============================================================")
    lines.append("")
    lines.append(f"static void gemm_ukernel_fp32_packed_{mr}x{nr}(")
    lines.append(f"        int K,")
    lines.append(f"        const float* __restrict__ packed_A,")
    lines.append(f"        const float* __restrict__ packed_B,")
    lines.append(f"        float* __restrict__ C, int ldc,")
    lines.append(f"        float alpha, float beta) {{")

    # Accumulator declarations: use named vars to force register allocation
    # Naming: acc{row}_{quad}, e.g. acc0_0, acc0_1, acc1_0, acc1_1
    acc_names = []
    for i in range(mr):
        row_accs = []
        for j in range(n_b):
            name = f"a{i}{j}"
            row_accs.append(name)
            acc_names.append(name)

    # Declare accumulators
    lines.append("")
    for name in acc_names:
        lines.append(f"    float32x4_t {name} = vdupq_n_f32(0);")

    lines.append("")
    lines.append(f"    const float* __restrict__ pA = packed_A;")
    lines.append(f"    const float* __restrict__ pB = packed_B;")

    # K-unrolled main loop
    lines.append("")
    lines.append(f"    // {k_unroll}x K-unrolled main loop")
    lines.append(f"    int k = 0;")
    lines.append(f"    for (; k + {k_unroll - 1} < K; k += {k_unroll}) {{")

    # Optional prefetch (only if enough K remaining)
    if k_unroll >= 2:
        lines.append(f"        if (k + {k_unroll * 4} < K) {{")
        lines.append(f'            __asm__ volatile("prfm pldl1keep, [%0]" : : "r"(pA + {mr * 4}) : "memory");')
        lines.append(f'            __asm__ volatile("prfm pldl1keep, [%0]" : : "r"(pB + {nr * 4}) : "memory");')
        lines.append(f"        }}")

    # Generate K_unroll iterations
    for ki in range(k_unroll):
        lines.append("")
        lines.append(f"        // K iteration {ki}")
        lines.append(f"        {{")

        # Load A quads: ceil(Mr/4) quads, each containing 4 row-values
        for aq in range(n_a):
            offset = aq * 4
            lines.append(f"            float32x4_t ar{aq} = vld1q_f32(pA + {offset});")
        lines.append(f"            pA += {mr};")

        # Load B quads
        for bq in range(n_b):
            offset = bq * 4
            lines.append(f"            float32x4_t b{bq} = vld1q_f32(pB + {offset});")
        lines.append(f"            pB += {nr};")

        # FMLA: for each row, for each B quad
        # ar{row//4}.s[row%4] gives the scalar for this row
        for i in range(mr):
            aq = i // 4
            lane = i % 4
            for j in range(n_b):
                acc = acc_names[i * n_b + j]
                lines.append(
                    f"            {acc} = vfmaq_laneq_f32({acc}, b{j}, ar{aq}, {lane});"
                )

        lines.append(f"        }}")

    lines.append(f"    }}")

    # K tail: single iteration at a time
    lines.append("")
    lines.append(f"    // K tail")
    lines.append(f"    for (; k < K; ++k) {{")

    for aq in range(n_a):
        offset = aq * 4
        lines.append(f"        float32x4_t ar{aq} = vld1q_f32(pA + {offset});")
    lines.append(f"        pA += {mr};")

    for bq in range(n_b):
        offset = bq * 4
        lines.append(f"        float32x4_t b{bq} = vld1q_f32(pB + {offset});")
    lines.append(f"        pB += {nr};")

    for i in range(mr):
        aq = i // 4
        lane = i % 4
        for j in range(n_b):
            acc = acc_names[i * n_b + j]
            lines.append(
                f"        {acc} = vfmaq_laneq_f32({acc}, b{j}, ar{aq}, {lane});"
            )

    lines.append(f"    }}")

    # Epilogue: store C = alpha * acc + beta * C
    lines.append("")
    lines.append(f"    // Epilogue: store C = alpha * acc + beta * C")
    lines.append(f"    float32x4_t av = vdupq_n_f32(alpha);")
    lines.append(f"    float32x4_t bv = vdupq_n_f32(beta);")

    for i in range(mr):
        lines.append(f"    {{")
        lines.append(f"        float* cr = C + {i} * ldc;")
        if i == 0:
            pass  # first row, cr = C

        for j in range(n_b):
            acc = acc_names[i * n_b + j]
            offset = j * 4
            if offset == 0:
                lines.append(f"        if (beta == 0.0f) {{")
                lines.append(f"            vst1q_f32(cr, vmulq_f32(av, {acc}));")
                for jj in range(1, n_b):
                    a2 = acc_names[i * n_b + jj]
                    o2 = jj * 4
                    lines.append(f"            vst1q_f32(cr + {o2}, vmulq_f32(av, {a2}));")
                lines.append(f"        }} else {{")
                lines.append(f"            vst1q_f32(cr, vfmaq_f32(vmulq_f32(av, {acc}), bv, vld1q_f32(cr)));")
                for jj in range(1, n_b):
                    a2 = acc_names[i * n_b + jj]
                    o2 = jj * 4
                    lines.append(f"            vst1q_f32(cr + {o2}, vfmaq_f32(vmulq_f32(av, {a2}), bv, vld1q_f32(cr + {o2})));")
                lines.append(f"        }}")
            # only generate once per row

        lines.append(f"    }}")

    lines.append(f"}}")
    return "\n".join(lines)


def gen_registry(mr, nr, priority):
    n_b = nr // 4
    total_acc = mr * n_b

    lines = []
    lines.append("")
    lines.append(f"// ============================================================")
    lines.append(f"// Registry wrappers + auto-registration")
    lines.append(f"// ============================================================")
    lines.append("")
    lines.append(f"namespace {{")
    lines.append("")
    lines.append(f"void ukernel_fp32_{mr}x{nr}_wrap(")
    lines.append(f"        int K, const void* packed_A, const void* packed_B,")
    lines.append(f"        float* C, int ldc, float alpha, float beta,")
    lines.append(f"        float /*extra*/) {{")
    lines.append(f"    gemm_ukernel_fp32_packed_{mr}x{nr}(")
    lines.append(f"        K,")
    lines.append(f"        static_cast<const float*>(packed_A),")
    lines.append(f"        static_cast<const float*>(packed_B),")
    lines.append(f"        C, ldc, alpha, beta);")
    lines.append(f"}}")
    lines.append("")
    lines.append(f"void pack_a_fp32_{mr}x{nr}_wrap(")
    lines.append(f"        int m_len, int k_len, const float* A, int lda,")
    lines.append(f"        void* packed_A, int /*Mr*/, float* /*scale_out*/) {{")
    lines.append(f"    pack_a_fp32_{mr}x{nr}(m_len, k_len, A, lda, static_cast<float*>(packed_A));")
    lines.append(f"}}")
    lines.append("")
    lines.append(f"void pack_b_fp32_{mr}x{nr}_wrap(")
    lines.append(f"        int k_len, int n_len, const float* B, int ldb,")
    lines.append(f"        void* packed_B, int /*Nr*/, float* /*scale_out*/) {{")
    lines.append(f"    pack_b_fp32_{mr}x{nr}(k_len, n_len, B, ldb, static_cast<float*>(packed_B));")
    lines.append(f"}}")
    lines.append("")

    # Descriptor
    lines.append(f"// Priority {priority}")
    lines.append(f"const GemmMicrokernelDesc neon_fp32_{mr}x{nr}_desc = {{")
    lines.append(f"    \"neon_fp32_{mr}x{nr}\",")
    lines.append(f"    GemmDataType::kFP32,")
    lines.append(f"    kNEON,")
    lines.append(f"    {mr},                    // Mr")
    lines.append(f"    {nr},                   // Nr")
    lines.append(f"    1,                    // Kgroup")
    lines.append(f"    false,                // nr_is_vla")
    lines.append(f"    {priority},                  // priority")
    lines.append(f"    sizeof(float),        // packed_a_elem_bytes")
    lines.append(f"    sizeof(float),        // packed_b_elem_bytes")
    lines.append(f"    0,                    // min_sve_bits")
    lines.append(f"    ukernel_fp32_{mr}x{nr}_wrap,")
    lines.append(f"    pack_a_fp32_{mr}x{nr}_wrap,")
    lines.append(f"    pack_b_fp32_{mr}x{nr}_wrap,")
    lines.append(f"}};")
    lines.append("")
    lines.append(f"static RegisterKernel reg_neon_fp32_{mr}x{nr}(neon_fp32_{mr}x{nr}_desc);")
    lines.append("")
    lines.append(f"}}  // namespace")
    lines.append("")
    lines.append(f"}}  // namespace dnnopt")
    lines.append(f"")
    lines.append(f"#endif  // __aarch64__")
    return "\n".join(lines)


def generate(mr, nr, k_unroll, priority):
    code = gen_header(mr, nr, k_unroll)
    code += gen_pack_a(mr, nr)
    code += gen_pack_b(mr, nr)
    code += gen_kernel(mr, nr, k_unroll)
    code += gen_registry(mr, nr, priority)
    return code


if __name__ == "__main__":
    if len(sys.argv) < 5:
        print(f"Usage: {sys.argv[0]} <Mr> <Nr> <K_unroll> <priority>", file=sys.stderr)
        print(f"  e.g. {sys.argv[0]} 4 16 4 110", file=sys.stderr)
        sys.exit(1)

    mr = int(sys.argv[1])
    nr = int(sys.argv[2])
    k_unroll = int(sys.argv[3])
    priority = int(sys.argv[4])

    # Validate
    if nr % 4 != 0:
        print(f"Error: Nr must be a multiple of 4, got {nr}", file=sys.stderr)
        sys.exit(1)
    if mr < 1 or mr > 16:
        print(f"Error: Mr must be 1-16, got {mr}", file=sys.stderr)
        sys.exit(1)

    n_b = nr // 4
    total_acc = mr * n_b
    if total_acc + n_b > 32:
        print(f"Warning: {mr}x{nr} = {total_acc} acc + {n_b} B = {total_acc + n_b} regs > 32",
              file=sys.stderr)

    print(generate(mr, nr, k_unroll, priority))
